"""empty message

Revision ID: a02d30971f71
Revises: bc1ff1fd340b
Create Date: 2018-06-07 15:01:55.786978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02d30971f71'
down_revision = 'bc1ff1fd340b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('photo_1', sa.String(length=100), nullable=True))
    op.add_column('t_user', sa.Column('photo_2', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'photo_2')
    op.drop_column('t_user', 'photo_1')
    # ### end Alembic commands ###
